User, car, hotel, room, booking models are added
Asifkhan-akhan/travel-booking-portal pull request #1
Opened 2023-10-23 08:26 UTC by Asifkhan-akhan

all the models are created

2023-10-23 09:12 UTC, OvaisTariq95 requested changes
Good Work

2023-10-23 09:12 UTC, OvaisTariq95 commented on models/car.go
> +type Car struct {
CarRental

2023-10-23 09:12 UTC, OvaisTariq95 commented on models/booking.go
> +	ServiceType string    `json:"service_type" bson:"service_type" db:"service_type" structs:"service_type"` // Either Hotel or Car
why we need this if we already have service id?

2023-10-23 09:12 UTC, OvaisTariq95 commented on models/car.go
> +	Model       string `json:"model" db:"model" structs:"model" bson:"model"`
irrelevant

2023-10-23 09:12 UTC, OvaisTariq95 commented on models/car.go
> +	Year        int    `json:"year" db:"year" structs:"year" bson:"year"`
irrelevant

2023-10-23 09:12 UTC, OvaisTariq95 commented on models/car.go
> +}
add a stus key aswell for booked/open

2023-10-23 09:35 UTC, Asifkhan-akhan commented on models/car.go
> +type Car struct {
changed

2023-10-23 09:35 UTC, Asifkhan-akhan commented on models/booking.go
> +	ServiceType string    `json:"service_type" bson:"service_type" db:"service_type" structs:"service_type"` // Either Hotel or Car
"Booking" is in one-to-one relation with CarRental and Room. so both (CarRental ,Room) can have same ids. So ServiceType will act as a flag between them.

2023-10-23 09:35 UTC, Asifkhan-akhan commented on models/car.go
> +	Model       string `json:"model" db:"model" structs:"model" bson:"model"`
removed

2023-10-23 09:35 UTC, Asifkhan-akhan commented on models/car.go
> +	Year        int    `json:"year" db:"year" structs:"year" bson:"year"`
removed

2023-10-23 09:35 UTC, Asifkhan-akhan commented on models/car.go
> +}
added

2023-10-24 07:38 UTC, OvaisTariq95 approved these changes

2023-10-24 07:41 UTC, merged