service layer added
Asifkhan-akhan/travel-booking-portal pull request #4
Opened 2023-11-03 06:20 UTC by Asifkhan-akhan

service layer is added with some minor improvement in db-layer and swagger yaml

2023-11-06 06:21 UTC, OvaisTariq95 requested changes
Good Work!

2023-11-06 06:21 UTC, OvaisTariq95 commented on db/datastore.go
> +	GetUser(searchCriteria map[string]interface{}) ([]*models.User, error)
Get calls means to return one record, if you are returning multiple objects its better to write func signature as ListUsers,ListHotels etc

2023-11-06 06:21 UTC, OvaisTariq95 commented on db/mongo/client.go
>  	"github.com/google/uuid"
sort imports

2023-11-06 06:21 UTC, OvaisTariq95 commented on main/main.go
> +	// Initialize your MongoDB client.
remove commented code prior to merging PR

2023-11-06 06:21 UTC, OvaisTariq95 commented on service/booking.go
> +	auth := smtp.PlainAuth("", "sayednur171@gmail.com", "qrmg auyg zclj cxjt", "smtp.gmail.com")
why are we hardcoding email address and other smtp settings ? define them in config.go so that we can change them and use them accordingly

2023-11-07 05:07 UTC, Asifkhan-akhan commented on db/datastore.go
> +	GetUser(searchCriteria map[string]interface{}) ([]*models.User, error)
changed to ListUser etc

2023-11-07 05:07 UTC, Asifkhan-akhan commented on db/mongo/client.go
>  	"github.com/google/uuid"
sorted

2023-11-07 05:07 UTC, Asifkhan-akhan commented on service/booking.go
> +	auth := smtp.PlainAuth("", "sayednur171@gmail.com", "qrmg auyg zclj cxjt", "smtp.gmail.com")
done

2023-11-08 04:37 UTC, OvaisTariq95 requested changes
Good work

2023-11-08 04:37 UTC, OvaisTariq95 commented on db/mongo/client.go
> +	if err != nil {
Remove extra line above, this err belongs to cursor so no need for newline

2023-11-08 04:37 UTC, OvaisTariq95 commented on db/mongo/client.go
> +	if err != nil {
Remove extra line above

2023-11-08 05:01 UTC, Asifkhan-akhan commented on db/mongo/client.go
> +	if err != nil {
removed

2023-11-08 05:01 UTC, Asifkhan-akhan commented on db/mongo/client.go
> +	if err != nil {
removed

2023-11-08 05:03 UTC, OvaisTariq95 approved these changes
GW!

2023-11-08 07:18 UTC, merged